version: '3.8'

services:
  remote-lsp-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remote-lsp-test
    ports:
      - "22:22"  # Map container SSH port to host port 2222
    volumes:
      # Optional: mount a local directory for persistent test files
      - ./test-workspace:/home/testuser/workspace
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    restart: unless-stopped
    networks:
      - lsp-network

networks:
  lsp-network:
    driver: bridge

