name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install StyLua
      run: |
        wget -O stylua.zip https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip
        unzip stylua.zip
        chmod +x stylua
        sudo mv stylua /usr/local/bin/

    - name: Check Lua formatting
      run: stylua --check lua/ tests/
