name: Run Lua Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Lua
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.3
        
    - name: Run tests
      run: lua tests/run_tests.lua